<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Fri Jun 13 18:56:29 COT 2014.

define('DOMJUDGE_VERSION', '3.4.0');

define('BINDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/bin');
define('ETCDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/etc');
define('WWWDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/www');
define('LIBDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/lib');
define('LIBEXTDIR',   '/home/civilian/repos/tg/domjudge-3.4.2/lib/ext');
define('LIBWWWDIR',   '/home/civilian/repos/tg/domjudge-3.4.2/lib/www');
define('LIBSUBMITDIR','/home/civilian/repos/tg/domjudge-3.4.2/lib/submit');
define('LOGDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/output/log');
define('RUNDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/output/run');
define('TMPDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/output/tmp');
define('SUBMITDIR',   '/home/civilian/repos/tg/domjudge-3.4.2/output/submissions');

define('SUBMIT_DEFAULT', 2);
define('ENABLE_CMDSUBMIT_SERVER', 1);
define('ENABLE_WEBSUBMIT_SERVER', 1);

set_include_path(get_include_path() . PATH_SEPARATOR . LIBEXTDIR);
