<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and judgehost-config.php

// Generated from 'judgehost-static.php.in' on Fri Jun 13 18:56:29 COT 2014.

define('DOMJUDGE_VERSION', '3.4.0');

define('BINDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/bin');
define('ETCDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/etc');
define('LIBDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/lib');
define('LIBJUDGEDIR', '/home/civilian/repos/tg/domjudge-3.4.2/lib/judge');
define('LOGDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/output/log');
define('RUNDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/output/run');
define('TMPDIR',      '/home/civilian/repos/tg/domjudge-3.4.2/output/tmp');
define('JUDGEDIR',    '/home/civilian/repos/tg/domjudge-3.4.2/output/judging');

define('RUNUSER',     'domjudge-run');
define('USE_CGROUPS', '0');
